
// Productos
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const POST_PRODUCT= 'POST_PRODUCT';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

//Store
export const GET_ALL_STORES = 'GET_ALL_STORES';
export const GET_STORE_DETAIL = 'GET_STORE_DETAIL';
export const POST_STORE = 'POST_STORE';
export const UPDATE_STORE = 'UPDATE_STORE';
export const DELETE_STORE = 'DELETE_STORE';

// relations
export const ASSOCIATE_PRODUCT_TO_STORE = 'ASSOCIATE_PRODUCT_TO_STORE';
export const ASSOCIATE_STORE_TO_PRODUCT = 'ASSOCIATE_STORE_TO_PRODUCT';
export const UPDATE_PRODUCT_STORE_ASSOCIATION = 'UPDATE_PRODUCT_STORE_ASSOCIATION';
export const DELETE_PRODUCT_STORE_ASSOCIATION = 'DELETE_PRODUCT_STORE_ASSOCIATION';
export const GET_STORES_ASSOCIATED_TO_PRODUCT = 'GET_STORES_ASSOCIATED_TO_PRODUCT';
export const GET_PRODUCTS_ASSOCIATED_TO_STORE = 'GET_PRODUCTS_ASSOCIATED_TO_STORE';

//User
export const USER_LOGIN = 'USER_LOGIN';
